version: '3.4'

x-default-node: &default-node
  image: dev.node:8
  build:
    context: .
    dockerfile: Dockerfile.node.dev
  environment:
    - DOCKERIZED=true
  volumes:
    - ./:/app
    - yarn_cache:/home/node/.cache
    - netlify:/home/node/.netlify
    - yarn_offline:/home/node/npm-packages-offline-cache

services:
  react:
    <<: *default-node
    entrypoint: /home/node/entrypoint.sh
    command: yarn start
    ports:
      - '3000:3000'
volumes:
  yarn_cache:
  netlify:
  yarn_offline:
